apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - rbac.yaml
  - configmap.yaml
  - llamacpp-service.yaml
  - llamacpp-daemonset.yaml
  - meta-router-deployment.yaml

namespace: default

commonLabels:
  managed-by: kustomize
  project: llamacpp-k8s-meta-router

images:
  - name: meta-router
    newName: meta-router
    newTag: latest
